### ISSUE TITLE
Exception in server tick loop||No Mixin Metadata is found in the Stacktrace.

### ISSUE THREAD

**Issue by tian-can151** [NovaEngineering-Source/StellarCore#15]
https://mclo.gs/7F9c0MO
Exception in server tick loop
53 |  
54 | java.lang.IllegalArgumentException: capacity: 1 (expected: >= 2)
55 | at github.kasuminova.stellarcore.shaded.org.jctools.util.RangeUtil.checkGreaterThanOrEqual(RangeUtil.java:63)
56 | at github.kasuminova.stellarcore.shaded.org.jctools.queues.MpmcArrayQueue.<init>(MpmcArrayQueue.java:175)
57 | at ic2.core.energy.grid.GridUpdater.stellar_core$createMpmcQueue(GridUpdater.java:792)
58 | at ic2.core.energy.grid.GridUpdater.handler$zoo000$stellar_core$startTransferCalc(GridUpdater.java:589)
59 | at ic2.core.energy.grid.GridUpdater.startTransferCalc(GridUpdater.java)
60 | at ic2.core.energy.grid.EnergyNetLocal.onTickStart(EnergyNetLocal.java:196)
61 | at ic2.core.energy.grid.EventHandler.onWorldTick(EventHandler.java:61)
62 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1032_EventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
63 | at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
64 | at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
65 | at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:289)
66 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:958)
67 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
68 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
69 | at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
70 | at java.lang.Thread.run(Thread.java:750)
71 |  
72 | No Mixin Metadata is found in the Stacktrace.
73

<br class="Apple-interchange-newline">
</body>
</html>Exception in server tick loop

java.lang.IllegalArgumentException: capacity: 1 (expected: >= 2)
	at github.kasuminova.stellarcore.shaded.org.jctools.util.RangeUtil.checkGreaterThanOrEqual(RangeUtil.java:63)
	at github.kasuminova.stellarcore.shaded.org.jctools.queues.MpmcArrayQueue.<init>(MpmcArrayQueue.java:175)
	at ic2.core.energy.grid.GridUpdater.stellar_core$createMpmcQueue(GridUpdater.java:792)
	at ic2.core.energy.grid.GridUpdater.handler$zoo000$stellar_core$startTransferCalc(GridUpdater.java:[58](https://mclo.gs/7F9c0MO#L58)9)
	at ic2.core.energy.grid.GridUpdater.startTransferCalc(GridUpdater.java)
	at ic2.core.energy.grid.EnergyNetLocal.onTickStart(EnergyNetLocal.java:196)
	at ic2.core.energy.grid.EventHandler.onWorldTick(EventHandler.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1032_EventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:289)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:958)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:[68](https://mclo.gs/7F9c0MO#L68)7)
	at java.lang.Thread.run(Thread.java:750)

No Mixin Metadata is found in the Stacktrace.

**Comment by KasumiNova** [comment]
Use latest version.
