### ISSUE TITLE
[Bug] java.lang.AbstractMethodError: net.minecraft.nbt.NBTTagByte.stellar_core$setPooled(Z)V

### ISSUE THREAD

**Issue by SherkeyXD** [NovaEngineering-Source/StellarCore#26]
## Version

StellarCore Version: 1.5.13
Java Version: Dragonwell-8
Minecraft Version: 1.12.2

## Brief Log
```java
[16:13:35] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
Caused by: java.lang.AbstractMethodError: net.minecraft.nbt.NBTTagByte.stellar_core$setPooled(Z)V
	at github.kasuminova.stellarcore.common.pool.NBTTagPrimitivePool.lambda$static$6(NBTTagPrimitivePool.java:33) ~[NBTTagPrimitivePool.class:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_422]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_422]
	at github.kasuminova.stellarcore.common.pool.NBTTagPrimitivePool.<clinit>(NBTTagPrimitivePool.java:33) ~[NBTTagPrimitivePool.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74774_a(NBTTagCompound.java:1192) ~[fy.class:?]
	at net.minecraft.item.ItemStack.func_77955_b(ItemStack.java:229) ~[aip.class:?]
	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1059) ~[aip.class:?]
	at net.minecraft.stats.StatList.func_151181_c(StatList.java:181) ~[qs.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:125) ~[qs.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:515) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 12 more
```

## Full Log

[latest.log](https://github.com/user-attachments/files/17827327/latest.log)

**Comment by KasumiNova** [comment]
Duplicate with #22.
