### ISSUE TITLE
`DisableRadiationCapability` breaking Trinity's explosions

### ISSUE THREAD

**Issue by Krutoy242** [NovaEngineering-Source/StellarCore#30]
When this option is enabled, bombs does not destroy blocks or damage entities

![image](https://github.com/user-attachments/assets/7b393525-c9e8-400c-b480-d3842146c5cf)
![image](https://github.com/user-attachments/assets/7a471919-b847-48f6-8eb8-060d7f880dd1)

This what player saw in log:
```less
Caused by: java.lang.NullPointerException
    at nc.radiation.RadiationHelper.addRadsToEntity(RadiationHelper.java:297)
    at trinity.explosion.ExplosionNukeGeneric.irradiate(ExplosionNukeGeneric.java:150)
    at trinity.blocks.NuclearCore.AtomicBomb(NuclearCore.java:106)
    at trinity.items.ItemDetonator.onItemRightClick(ItemDetonator.java:75)
    at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:217)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:358)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItem(NetHandlerPlayServer.java:765)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:32)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(SourceFile:9)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more
```

Happens on [E2EE](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack.

**Comment by KasumiNova** [comment]
Simply turn this option off, as the essential effect is to disable the nc's radiation system.

**Comment by Krutoy242** [comment]
But I want both - I want **radiation to be disabled** AND trinity bombs exploding. Explosions (destruction of blocks) is not related to radiation.

**Comment by KasumiNova** [comment]
mod name?

**Comment by Krutoy242** [comment]
> mod name?

["Trinity"](https://www.curseforge.com/minecraft/mc-mods/trinity)
