### ISSUE TITLE
Possibly Add fixes for Moar Boats

### ISSUE THREAD

**Issue by helixyuri** [NovaEngineering-Source/StellarCore#6]
The latest version Moar boats crashes with a connection lost screen due to an issue with one of it's packets.
 I was wondering if this bug can be solved with a simple fix.
![error](https://github.com/user-attachments/assets/cf966882-038f-4eb3-b339-06e89310e424)

SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38)
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93)
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120)
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:236)
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.updateModuleData(ModularBoatEntity.kt:329)
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.saveState(ModularBoatEntity.kt:297)
	at org.jglrxavpok.moarboats.common.state.BoatProperty.set(BoatProperty.kt:25)
	at org.jglrxavpok.moarboats.common.modules.BaseEngineModule.update(BaseEngineModule.kt:86)
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.onUpdate(ModularBoatEntity.kt:138)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
	at net.minecraft.world.World.updateEntity(World.java:1958)
	at net.minecraft.world.World.updateEntities(World.java:1762)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
	at java.lang.Thread.run(Thread.java:745)
------

Netty Server IO #1
There was a critical exception handling a packet on channel moarboats
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38)
	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93)
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$3.selectNetworks(FMLOutboundHandler.java:120)
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:236)
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.updateModuleData(ModularBoatEntity.kt:329)
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.saveState(ModularBoatEntity.kt:297)
	at org.jglrxavpok.moarboats.common.state.BoatProperty.set(BoatProperty.kt:25)
	at org.jglrxavpok.moarboats.common.modules.BaseEngineModule.update(BaseEngineModule.kt:86)
	at org.jglrxavpok.moarboats.common.entities.ModularBoatEntity.onUpdate(ModularBoatEntity.kt:138)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
	at net.minecraft.world.World.updateEntity(World.java:1958)
	at net.minecraft.world.World.updateEntities(World.java:1762)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
	at java.lang.Thread.run(Thread.java:745)

**Comment by KasumiNova** [comment]
Moar boats is written in Kotlin, I'm sorry but I don't have decompiler that can check Kotlin classes, so I can't fix it.
